version: '3.8'

services:
  feedback-app:
    build:
      context: .

    container_name: feedback-app

    restart: unless-stopped

    volumes:
      - /home/pi/fileData:/dataFiles
    
    ports:
      - "8080:8080"